server:
  port: 8082

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/catalog?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:pixelmart}
    password: ${MYSQL_PASSWORD:pixelmart}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: catalog
  flyway:
    enabled: true
    schemas: catalog
    default-schema: catalog
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

pixelmart:
  internal:
    allowed-service: order-service
  order:
    base-url: ${ORDER_SERVICE_URL:http://localhost:8083}
    internal-service-name: catalog-service
  auth:
    base-url: ${AUTH_SERVICE_URL:http://localhost:8081}
    internal-service-name: catalog-service
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      base-path: ${STORAGE_LOCAL_PATH:./data/uploads}
    s3:
      region: ${AWS_REGION:us-east-1}
      bucket: ${AWS_S3_BUCKET:}
      prefix: ${AWS_S3_PREFIX:pixelmart}

management:
  endpoints:
    web:
      exposure:
        include: health,info
