server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/pixelmart?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:pixelmart}
    password: ${MYSQL_PASSWORD:pixelmart}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: notify
  flyway:
    enabled: true
    schemas: notify
    default-schema: notify
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
