CREATE DATABASE IF NOT EXISTS pixelmart CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pixelmart;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS notify;

GRANT ALL PRIVILEGES ON pixelmart.* TO 'pixelmart'@'%';
FLUSH PRIVILEGES;
